Repository deephunt3r/Bugbounty, pull requests merged in 2021-10, with the labels that each got.

#6 Create stale.yml
  .github/workflows/stale.yml
Labels: enhancement, Hacktoberfest, hacktoberfest-accepted

#7 Create community.yml
  workflows/community.yml
Labels: enhancement, Hacktoberfest, hacktoberfest-accepted

#8 Create pull_request_template.md
  .github/pull_request_template.md
Labels: enhancement, good first issue, Hacktoberfest, hacktoberfest-accepted

#5 Update bugbountydorks.txt
  dorks/bugbountydorks.txt
Labels: hacktoberfest-accepted

#10 Create howto-Find-Program-bugbounty.md
  writeups/howto-Find-Program-bugbounty.md
Labels: hacktoberfest-accepted
